# Домашнее задание к лекции "Базовые понятия статистики"


In [200]:
import pandas as pd
import numpy as np

## Задание 1. Загрузка данных

Изучить представленный набор данных на основе описания его столбцов, загрузить его и оставить 8 столбцов для дальнейшего изучения: 
surgery, Age, rectal temperature, pulse, respiratory rate, temperature of extremities, pain, outcome.



In [201]:
df=pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv', header=None,na_values='?')
df.head(60)


0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0   2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1   1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2   2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3   1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4   2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   
5   2.0   1   528355   NaN    NaN   NaN  2.0  1.0  3.0  1.0  ...   NaN   NaN   
6   1.0   1   526802  37.9   48.0  16.0  1.0  1.0  1.0  1.0  ...  37.0   7.0   
7   1.0   1   529607   NaN   60.0   NaN  3.0  NaN  NaN  1.0  ...  44.0   8.3   
8   2.0   1   530051   NaN   80.0  36.0  3.0  4.0  3.0  1.0  ...  38.0   6.2   
9   2.0   9  5299629  38.3   90.0   NaN  1.0  NaN  1.0  1.0  ...  40.0   6.2   
10  1.0   1   528548  38.1   66.0  12.0  3.0  3.0  5.0  1.0  ...  44.0   6.0   
11  2.0   1   527927  39.1   72.0  52.0  2.0  NaN  2.0  1.0  ...  50.0   7.8   
12  1.0   1   528031  37.2   42.0  12.0  2.0  1.0  1.0  1.0  ...   NaN   7.0   
13  2.0   9  5291329  38.0   92.0  28.0  1.0  1.0  2.0  1.0  ...  37.0   6.1   
14  1.0   1   534917  38.2   76.0  28.0  3.0  1.0  1.0  1.0  ...  46.0  81.0   
15  1.0   1   530233  37.6   96.0  48.0  3.0  1.0  4.0  1.0  ...  45.0   6.8   
16  1.0   9  5301219   NaN  128.0  36.0  3.0  3.0  4.0  2.0  ...  53.0   7.8   
17  2.0   1   526639  37.5   48.0  24.0  NaN  NaN  NaN  NaN  ...   NaN   NaN   
18  1.0   1  5290481  37.6   64.0  21.0  1.0  1.0  2.0  1.0  ...  40.0   7.0   
19  2.0   1   532110  39.4  110.0  35.0  4.0  3.0  6.0  NaN  ...  55.0   8.7   
20  1.0   1   530157  39.9   72.0  60.0  1.0  1.0  5.0  2.0  ...  46.0   6.1   
21  2.0   1   529340  38.4   48.0  16.0  1.0  NaN  1.0  1.0  ...  49.0   6.8   
22  1.0   1   521681  38.6   42.0  34.0  2.0  1.0  4.0  NaN  ...  48.0   7.2   
23  1.0   9   534998  38.3  130.0  60.0  NaN  3.0  NaN  1.0  ...  50.0  70.0   
24  1.0   1   533692  38.1   60.0  12.0  3.0  3.0  3.0  1.0  ...  51.0  65.0   
25  2.0   1   529518  37.8   60.0  42.0  NaN  NaN  NaN  1.0  ...   NaN   NaN   
26  1.0   1   530526  38.3   72.0  30.0  4.0  3.0  3.0  2.0  ...  43.0   7.0   
27  1.0   1   528653  37.8   48.0  12.0  3.0  1.0  1.0  1.0  ...  37.0   5.5   
28  1.0   1  5279442   NaN    NaN   NaN  NaN  NaN  NaN  NaN  ...   NaN   NaN   
29  2.0   1   535415  37.7   48.0   NaN  2.0  1.0  1.0  1.0  ...  45.0  76.0   
30  2.0   1   529475  37.7   96.0  30.0  3.0  3.0  4.0  2.0  ...  66.0   7.5   
31  2.0   1   530242  37.2  108.0  12.0  3.0  3.0  4.0  2.0  ...  52.0   8.2   
32  1.0   1   529427  37.2   60.0   NaN  2.0  1.0  1.0  1.0  ...  43.0   6.6   
33  1.0   1   529663  38.2   64.0  28.0  1.0  1.0  1.0  1.0  ...  49.0   8.6   
34  1.0   1   529796   NaN  100.0  30.0  3.0  3.0  4.0  2.0  ...  52.0   6.6   
35  2.0   1   528812   NaN  104.0  24.0  4.0  3.0  3.0  2.0  ...  73.0   8.4   
36  2.0   1   529493  38.3  112.0  16.0  NaN  3.0  5.0  2.0  ...  51.0   6.0   
37  1.0   1   533847  37.8   72.0   NaN  NaN  3.0  NaN  1.0  ...  56.0  80.0   
38  2.0   1   528996  38.6   52.0   NaN  1.0  1.0  1.0  1.0  ...  32.0   6.6   
39  1.0   9  5277409  39.2  146.0  96.0  NaN  NaN  NaN  NaN  ...   NaN   NaN   
40  1.0   1   529498   NaN   88.0   NaN  3.0  3.0  6.0  2.0  ...  63.0   6.5   
41  2.0   9  5288249  39.0  150.0  72.0  NaN  NaN  NaN  NaN  ...  47.0   8.5   
42  2.0   1   530301  38.0   60.0  12.0  3.0  1.0  3.0  1.0  ...  47.0   7.0   
43  1.0   1   534069   NaN  120.0   NaN  3.0  4.0  4.0  1.0  ...  52.0  67.0   
44  1.0   1   535407  35.4  140.0  24.0  3.0  3.0  4.0  2.0  ...  57.0  69.0   
45  2.0   1   529827   NaN  120.0   NaN  4.0  3.0  4.0  2.0  ...  60.0   6.5   
46  1.0   1   529888  37.9   60.0  15.0  3.0  NaN  4.0  2.0  ...  65.0   7.5   
47  2.0   1   529821  37.5   48.0  16.0  1.0  1.0  1.0  1.0  ...  37.0   6.5   
48  1.0   1   528890  38.9   80.0  44.0  3.0  3.0  3.0  2.0  ...  54.0   6.5   
49  2

In [202]:
horses_info=df.iloc[:,[0,1,3,4,5,6,10,22]]
horses_info.columns=['surgery','age','rectal temperature','pulse','respiratory rate','temperature of extremities','pain','outcome']
horses_info.head(15)

surgery  age  rectal temperature  pulse  respiratory rate  \
0       2.0    1                38.5   66.0              28.0   
1       1.0    1                39.2   88.0              20.0   
2       2.0    1                38.3   40.0              24.0   
3       1.0    9                39.1  164.0              84.0   
4       2.0    1                37.3  104.0              35.0   
5       2.0    1                 NaN    NaN               NaN   
6       1.0    1                37.9   48.0              16.0   
7       1.0    1                 NaN   60.0               NaN   
8       2.0    1                 NaN   80.0              36.0   
9       2.0    9                38.3   90.0               NaN   
10      1.0    1                38.1   66.0              12.0   
11      2.0    1                39.1   72.0              52.0   
12      1.0    1                37.2   42.0              12.0   
13      2.0    9                38.0   92.0              28.0   
14      1.0    1                38.2   76.0              28.0   

    temperature of extremities  pain  outcome  
0                          3.0   5.0      2.0  
1                          NaN   3.0      3.0  
2                          1.0   3.0      1.0  
3                          4.0   2.0      2.0  
4                          NaN   NaN      2.0  
5                          2.0   2.0      1.0  
6                          1.0   3.0      1.0  
7                          3.0   NaN      2.0  
8                          3.0   4.0      3.0  
9                          1.0   5.0      1.0  
10                         3.0   3.0      1.0  
11                         2.0   2.0      1.0  
12                         2.0   3.0      1.0  
13                         1.0   1.0      2.0  
14                         3.0   3.0      1.0

## Задание 2. Первичное изучение данных

Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы.



In [203]:
horses_info.describe()

surgery         age  rectal temperature       pulse  \
count  299.000000  300.000000          240.000000  276.000000   
mean     1.397993    1.640000           38.167917   71.913043   
std      0.490305    2.173972            0.732289   28.630557   
min      1.000000    1.000000           35.400000   30.000000   
25%      1.000000    1.000000           37.800000   48.000000   
50%      1.000000    1.000000           38.200000   64.000000   
75%      2.000000    1.000000           38.500000   88.000000   
max      2.000000    9.000000           40.800000  184.000000   

       respiratory rate  temperature of extremities       pain     outcome  
count        242.000000                  244.000000  245.00000  299.000000  
mean          30.417355                    2.348361    2.95102    1.551839  
std           17.642231                    1.045054    1.30794    0.737187  
min            8.000000                    1.000000    1.00000    1.000000  
25%           18.500000                    1.000000    2.00000    1.000000  
50%           24.500000                    3.000000    3.00000    1.000000  
75%           36.000000                    3.000000    4.00000    2.000000  
max           96.000000                    4.000000    5.00000    3.000000

In [204]:
horses_info.surgery.unique()

array([ 2.,  1., nan])

In [205]:
horses_info.age.unique()

array([1, 9], dtype=int64)

In [217]:
#нормальная температура 37,8
horses_info['rectal temperature'].unique()

#уберем значения выходящие за пределы межквартильного размаха (14шт)

array([38.5, 39.2, 38.3, 39.1, 37.3,  nan, 37.9, 38.1, 37.2, 38. , 38.2,
       37.6, 37.5, 39.4, 39.9, 38.4, 38.6, 37.8, 37.7, 39. , 35.4, 38.9,
       37.4, 40.3, 37. , 39.7, 38.7, 36.4, 38.8, 39.6, 36.8, 39.5, 36.5,
       36. , 37.1, 39.3, 36.1, 36.6, 40.8, 36.9, 40. ])

In [240]:
q1 = horses_info['rectal temperature'].quantile(0.25)
q3 = horses_info['rectal temperature'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
print(lower_bound ,upper_bound)
horses_info.loc[(horses_info['rectal temperature'] is None) | (horses_info['rectal temperature'].between(lower_bound, upper_bound, inclusive=True))]
#city_df = city_df.loc[city_df['Площадь'] > 1000]


36.74999999999999 39.550000000000004


surgery  age  rectal temperature  pulse  respiratory rate  \
0        2.0    1                38.5   66.0              28.0   
1        1.0    1                39.2   88.0              20.0   
2        2.0    1                38.3   40.0              24.0   
3        1.0    9                39.1  164.0              84.0   
4        2.0    1                37.3  104.0              35.0   
..       ...  ...                 ...    ...               ...   
292      1.0    1                37.0   66.0              20.0   
294      2.0    1                38.5   40.0              16.0   
296      2.0    1                37.2   72.0              24.0   
297      1.0    1                37.5   72.0              30.0   
299      1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
0                           3.0   5.0      2.0  
1                           NaN   3.0      3.0  
2                           1.0   3.0      1.0  
3                           4.0   2.0      2.0  
4                           NaN   NaN      2.0  
..                          ...   ...      ...  
292                         1.0   4.0      2.0  
294                         1.0   2.0      1.0  
296                         3.0   4.0      3.0  
297                         4.0   4.0      2.0  
299                         NaN   NaN      3.0  

[226 rows x 8 columns]

In [223]:
horses_info_remove['rectal temperature'].unique()

array([38.5, 39.2, 38.3, 39.1, 37.3, 37.9, 38.1, 37.2, 38. , 38.2, 37.6,
       37.5, 39.4, 38.4, 38.6, 37.8, 37.7, 39. , 38.9, 37.4, 37. , 38.7,
       38.8, 36.8, 39.5, 37.1, 39.3, 36.9])

In [219]:
#нормальный пульс 30-40 (20-25 для беговых), при болевом шоке учащается
horses_info.pulse.unique()

#данные из таблицы значительно превосходят нормальные показатели и могут считаться выбросами значения превышающие 120 ("пальцем в небо") 

array([ 66.,  88.,  40., 164., 104.,  nan,  48.,  60.,  80.,  90.,  72.,
        42.,  92.,  76.,  96., 128.,  64., 110., 130., 108., 100., 112.,
        52., 146., 150., 120., 140.,  84.,  46., 114., 160.,  54.,  56.,
        38.,  98.,  50.,  44.,  70.,  78.,  49.,  30., 136., 132.,  65.,
        86., 129.,  68.,  36.,  45., 124., 184.,  75.,  82.])

In [215]:
horses_info_=horses_info_remove[(horses_info_remove.pulse<120)|(horses_info_remove['pulse'] is None)]
horses_info_

surgery  age  rectal temperature  pulse  respiratory rate  \
0        2.0    1                38.5   66.0              28.0   
1        1.0    1                39.2   88.0              20.0   
2        2.0    1                38.3   40.0              24.0   
4        2.0    1                37.3  104.0              35.0   
6        1.0    1                37.9   48.0              16.0   
..       ...  ...                 ...    ...               ...   
292      1.0    1                37.0   66.0              20.0   
294      2.0    1                38.5   40.0              16.0   
296      2.0    1                37.2   72.0              24.0   
297      1.0    1                37.5   72.0              30.0   
299      1.0    1                37.2   40.0              20.0   

     temperature of extremities  pain  outcome  
0                           3.0   5.0      2.0  
1                           NaN   3.0      3.0  
2                           1.0   3.0      1.0  
4                           NaN   NaN      2.0  
6                           1.0   3.0      1.0  
..                          ...   ...      ...  
292                         1.0   4.0      2.0  
294                         1.0   2.0      1.0  
296                         3.0   4.0      3.0  
297                         4.0   4.0      2.0  
299                         NaN   NaN      3.0  

[200 rows x 8 columns]

In [216]:
#нормальный пульс 30-40 (20-25 для беговых), при болевом шоке учащается
horses_info_.pulse.unique()

array([ 66.,  88.,  40., 104.,  48.,  90.,  72.,  42.,  92.,  76.,  96.,
        64., 110.,  60., 108., 112.,  52.,  80.,  84.,  46.,  54.,  56.,
        38., 100.,  50.,  44.,  49.,  30.,  86.,  68.,  36.,  45.,  70.,
        75.,  82.])

In [176]:
#нормальная частота дыхания 8 to 10
horses_info_['respiratory rate'].unique()

# в данном столбце 58 пропусков, большой размах значений, ско -17.642231, 
# также дополнительно в описании таблицы указано, что полезность этих данных сомнительна в виду большой флуктуации.
# я считаю, что пропущенные данные в этом столбце восстанавливать нецелесообразно, его можно удалить.

array([28., 20., 24., 84., 35., nan, 16., 36., 12., 52., 48., 21., 60.,
       34., 42., 30., 96., 72., 15., 44., 32., 22., 18., 80., 40., 10.,
       51., 68., 66.,  9., 14., 90.,  8., 23., 58., 13., 70., 26., 88.,
       25., 50.])

In [196]:
horses_info_['temperature of extremities'].unique()

array([ 3., nan,  1.,  2.,  4.])

In [197]:
horses_info_.pain.unique()

array([ 5.,  3., nan,  2.,  1.,  4.])

In [198]:
horses_info_.outcome.unique()

array([ 2.,  3.,  1., nan])

## Задание 3. Работа с пропусками

Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе заполнения пропусков по каждому столбцу на основе рассчитанных статистик и возможной взаимосвязи значений в них. Сформировать датафрейм, в котором пропуски будут отсутствовать.

In [199]:
(horses_info_.isna().mean()*100).round(2)

surgery                        0.5
age                            0.0
rectal temperature             0.0
pulse                          0.0
respiratory rate              11.5
temperature of extremities    17.5
pain                          17.0
outcome                        0.5
dtype: float64

### Age 

In [148]:
horses_info.age.unique()


array([1, 9], dtype=int64)

Согласно документации, столбец age должен содержать след значения : 1 = Adult horse
                                                                    2 = Young (< 6 months)
Можно выдвинуть гипотезу о том, что при заполнении данных произошла ошибка и заменить во всех строках "9" на "2"          

In [241]:
horses_info.loc[horses_info.age == 9,'age']=2
horses_info.head()

C:\Users\MAnnet\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


surgery  age  rectal temperature  pulse  respiratory rate  \
0      2.0    1                38.5   66.0              28.0   
1      1.0    1                39.2   88.0              20.0   
2      2.0    1                38.3   40.0              24.0   
3      1.0    2                39.1  164.0              84.0   
4      2.0    1                37.3  104.0              35.0   

   temperature of extremities  pain  outcome  
0                         3.0   5.0      2.0  
1                         NaN   3.0      3.0  
2                         1.0   3.0      1.0  
3                         4.0   2.0      2.0  
4                         NaN   NaN      2.0

In [152]:
horses_info.describe()

surgery         age  rectal temperature       pulse  \
count  299.000000  300.000000          240.000000  276.000000   
mean     1.397993    1.080000           38.167917   71.913043   
std      0.490305    0.271746            0.732289   28.630557   
min      1.000000    1.000000           35.400000   30.000000   
25%      1.000000    1.000000           37.800000   48.000000   
50%      1.000000    1.000000           38.200000   64.000000   
75%      2.000000    1.000000           38.500000   88.000000   
max      2.000000    2.000000           40.800000  184.000000   

       respiratory rate  temperature of extremities       pain     outcome  
count        242.000000                  244.000000  245.00000  299.000000  
mean          30.417355                    2.348361    2.95102    1.551839  
std           17.642231                    1.045054    1.30794    0.737187  
min            8.000000                    1.000000    1.00000    1.000000  
25%           18.500000                    1.000000    2.00000    1.000000  
50%           24.500000                    3.000000    3.00000    1.000000  
75%           36.000000                    3.000000    4.00000    2.000000  
max           96.000000                    4.000000    5.00000    3.000000